### ISSUE TITLE
ImportError: cannot import name '__all__'

### ISSUE THREAD

**Issue by ahvahsky2008** [cjlin1/libsvm#143]
i have troubles with running demo proj
```
root@Ubuntu-1704-zesty-64-minimal ~/phash/Python # python3.6 brisquequality.py 1.JPG
Traceback (most recent call last):
  File "brisquequality.py", line 24, in <module>
    # AGGD fit model, takes input as the MSCN Image / Pair-wise Product
  File "/root/phash/Python/libsvm/python/svmutil.py", line 6, in <module>
    from svm import __all__ as svm_all
ImportError: cannot import name '__all__
```

**Comment by cjlin1** [comment]
Sorry for the late response. I guess the reason is that svm.py is not on 
your path.. You can add files in libsvm/python directory in your path at 
runtime.
